name: Bug Report
description: Template for reporting bugs
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report a bug. Please fill out the following information."

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: |
        A clear and concise description of the bug. Include any information to reproduce your issue, e.g.,
        * full error messages and/or logs
        * Python code snippet
        * expected behavior
        * actual behaviour you encountered
      placeholder: |
        I am trying to do XYZ, but I am seeing the following error:
        ```
        <error message here>
        ```
        My Python script is:
        ```python
        import kumoai as kumo
        ...
        ```
        The Google Colab notebook is available at https://colab.research.google.com/...
        The data used in the Python script or notebook is available at ...
    validations:
      required: true

  - type: input
    id: kumoai_version
    attributes:
      label: `kumoai` version
      description: |
        Paste the value of:
        ```python
        import kumoai
        print(kumoai.__version__)
        ```
        or the output of:
        ```bash
        pip list
        ```
      placeholder: "e.g., 2.5.1"

  - type: input
    id: contact_information
    attributes:
      label: Contact Information
      description: "Best way to reach you if we need additional information"
      placeholder: "name@email.com"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Any other relevant context."
