name: Bug Report
description: Template for reporting bugs
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report a bug. Please fill out the following information."

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of the bug."
    validations:
      required: true

  - type: textarea
    id: sample_data
    attributes:
      label: Sample Data
      description: "If possible, provide sample data that's related to the issue."

  - type: textarea
    id: code_snippet
    attributes:
      label: Code Snippet
      description: "Provide any relevant code snippets."
      render: yaml

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What you expected to happen."

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happened."

  - type: textarea
    id: errors
    attributes:
      label: Error Messages
      description: "Paste any error messages or logs here."

  - type: input
    id: kumoai_version
    attributes:
      label: kumoai_version
      description: "Specify the kumoai version."
      placeholder: "e.g., 1.2"

  - type: input
    id: contact_information
    attributes:
      label: contact
      description: "Best way to reach you if we need additional information"
      placeholder: "name@email.com"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Any other relevant context."
